//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cub
{
    using System;
    using System.Collections.Generic;
    
    public partial class apartamentos_tabela
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public apartamentos_tabela()
        {
            this.pagamentos_tabela = new HashSet<pagamentos_tabela>();
        }
    
        public int id { get; set; }
        public string descricao { get; set; }
        public Nullable<System.DateTime> data_compra { get; set; }
        public decimal cub_quando_comprado { get; set; }
        public decimal valor_em_cub { get; set; }
        public decimal valor_parcela_cub { get; set; }
        public Nullable<decimal> valor_reforco_cub { get; set; }
        public decimal valor_pago_reais { get; set; }
        public decimal valor_pago_cub { get; set; }
        public decimal saldo_devedor_cub { get; set; }
        public decimal valor_em_reais { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<pagamentos_tabela> pagamentos_tabela { get; set; }
    }
}
