//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cub
{
    using System;
    using System.Collections.Generic;
    
    public partial class cub_tabela
    {
        public decimal valor_atual_do_cub { get; set; }
        public int id { get; set; }
    }
}
