//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace cub
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class aluguel_bancoEntities3 : DbContext
    {
        public aluguel_bancoEntities3()
            : base("name=aluguel_bancoEntities3")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<apartamentos_tabela> apartamentos_tabela { get; set; }
        public virtual DbSet<cub_tabela> cub_tabela { get; set; }
        public virtual DbSet<pagamentos_tabela> pagamentos_tabela { get; set; }
    }
}
